var riot = require('riot')
var d3 = require('d3')
var test = require('./tags/test.tag')
var hello = require('./tags/hello.tag')
var sel = require('./tags/sel.tag')
var todo = require('./tags/todo.tag')
var hello2 = require('./tags/hello2.tag')
var todo2 = require('./tags/todo2.tag')
var dt3 = require('./tags/dt3.tag')
riot.mount(test)
riot.mount(hello, {name: 'Jesse'})
riot.mount(sel)
riot.mount(todo)
riot.mount(hello2)
riot.mount(todo2)
riot.mount(dt3)
